---
title: "TitanicAnalysis"
author: "AmyHs , slimykat , Rabbit55"
date: "2018???5???2???"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#套件???
```{r}
library(ggplot2)
library(e1071)
library(knitr)
```

#資???
```{r}
train<-read.csv("titanicTrain.csv")
train<-train[-c(1001:1310),]
quest<-read.csv("titanicQuestion.csv")
train<-rbind(train,train)
```

#資???缺失???
```{r}
is_na<-function(x){
  sum(is.na(x))
}
sapply(train,is_na)
sapply(quest,is_na)
```

#資???探???
##0.1資?????????
```{r}
train$survived<-as.factor(train$survived)
train$pclass<-as.ordered(train$pclass)
```

##0.2??別???死???
```{r}
ggplot(train[!is.na(train$survived),], aes(x = sex, fill = survived)) +
  geom_bar(stat='count', position='dodge') + theme_grey() +
  labs(x = 'Training data only') +
  geom_label(stat='count', aes(label=..count..))
```

##0.3死亡???pclass
###0.3.1 class???死???
```{r}
ggplot(train[!is.na(train$survived),], aes(x = pclass, fill = survived)) +
  geom_bar(stat='count', position='dodge') + labs(x = 'Training data only') +
  theme(legend.position="none") 
```

###0.3.2 class& sex &死亡
```{r}
ggplot(train[!is.na(train$survived),], aes(x = pclass, fill = survived)) +
  geom_bar(stat='count', position='fill') +
  labs(x = 'Training data only', y= "Percent") + facet_grid(.~sex) 
```

##0.4 fare&死亡
```{r}
train[train$fare==0,]
#?????????class1中fare=0???人很??????好???票???跟?????????年齡???直??????聯??????出???
ggplot(train[!is.na(train$survived),], aes(x = fare, fill = survived)) +
  geom_histogram( bins= 30) +
  labs(x = 'Training data only', y= "Count") + facet_grid(.~pclass)
#??????出??麼??????
```

##0.5 缺失????????
###0.5.1???解決boat???缺失??
```{r}
train$boat = as.numeric(train$boat != "")
```

###0.5.2??????????????????測年?????缺失??
```{r}
agelm <- lm(age ~ pclass+boat+sex+parch+sibsp, data=train[!is.na(train$age),])
#?????下哪???????測??????好，以???R^2?
summary(agelm)
train$agelm<-predict(agelm,train)
```

###0.5.3???測結?????????
```{r}
hist(train$age[!is.na(train$age)], main='Original data, non-missing', xlab='age')
hist(train$agelm, main= 'LM predictions', xlab='age', xlim=range(0:80))
```

###0.5.4將缺???????
```{r}
indexMissingAge <- which(is.na(train$age))
train$age[indexMissingAge] <- train$agelm[indexMissingAge]

fare_NAindex = which(is.na(train$fare))
#????????????3701???票??????客人在fare factor??????na
temp = train$fare[nchar( as.character(train$ticket)) == 4 & grepl("^3",as.character(train$ticket))]
average = sum(temp[!is.na(temp)])/(length(temp)-1)
train[fare_NAindex,"fare"] = average
#將???似票根??????票??????平???

#將?????????????????????????
female_insea = train[train$sex == "female" & train$boat == 0,c("age","fare","survived")]
female_onboat = train[train$sex == "female" & train$boat == 1,c("age","fare","survived")]
male_insea = train[train$sex == "male" & train$boat == 0,c("age","fare","survived")]
male_onboat = train[train$sex == "male" & train$boat == 1,c("age","fare","survived")]

female_insea[,3] = as.factor(female_insea[,3])
female_onboat[,3] = as.factor(female_onboat[,3])
male_insea[,3] = as.factor(male_insea[,3])
male_onboat[,3] = as.factor(male_onboat[,3])

#對fare???log10減???數??????移
female_insea[,2] = log10(female_insea[,2])
female_onboat[,2] = as.factor(female_onboat[,2])
male_insea[,2] = as.factor(male_insea[,2])
male_onboat[,2] = as.factor(male_onboat[,2])
```

##0.5 SVM
```{r}
#???別對???????塊???SVM

plot_svm <- function(dat){
  survived = as.numeric(dat[,3])
  train_index = !is.na(survived)
  svmfit = svm(survived[train_index] ~ ., data = dat[train_index,],gamma = 1, cost = 100)
  return(svmfit)
}
par(mfrow=c(2,2))

svm1 = plot_svm(female_insea)
#plot(temp,female_insea[!is.na(female_insea$survived),])
svm2 = plot_svm(female_onboat)
# plot(temp,female_onboat[!is.na(female_onboat$survived),])
svm3 = plot_svm(male_insea)
# plot(temp,male_insea[!is.na(male_insea$survived),])
svm4 = plot_svm(male_onboat)
# plot(temp,male_onboat[!is.na(male_onboat$survived),])

outcome1 = data.frame(predict(svm1,female_insea[is.na(female_insea$survived),c(1:2)]))
outcome2 = data.frame(predict(svm2,female_onboat[is.na(female_onboat$survived),c(1:2)]))
outcome3 = data.frame(predict(svm3,male_insea[is.na(male_insea$survived),c(1:2)]))
outcome4 = data.frame(predict(svm4,male_onboat[is.na(male_onboat$survived),c(1:2)]))

#???併結????????輸???
names(outcome1) = "y"
names(outcome2) = "y"
names(outcome3) = "y"
names(outcome4) = "y"

ans = rbind(outcome1,outcome2,outcome3,outcome4)
index = order(row.names(ans))
ans = ans[index,]
write.csv(ans,file="titanicPrediction.csv")

kable(ans)
```

